name: Deploy Sphinx Documentation to Pages

on:
  push:
    branches: [main] # Se déclenche quand tu push sur main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Sphinx and dependencies
        run: |
          pip install --upgrade pip
          pip install sphinx furo sphinx-copybutton

      - name: Build HTML
        run: |
          sphinx-build -b html docs/source docs/build/html

      - name: Add .nojekyll
        run: touch docs/build/html/.nojekyll

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/build/html/

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
